# -*- coding: utf-8 -*-
"""health insurance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GR_pq3xfTUzbwpexIVGvqIYNqbU2QXyW
"""

!pip install streamlit pandas scikit-learn openai joblib

import pandas as pd
from sklearn.linear_model import LinearRegression
import joblib

df = pd.read_csv("https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/insurance.csv")

X = df[['age', 'bmi', 'children']]
y = df['charges']

model = LinearRegression()
model.fit(X, y)

joblib.dump(model, "model.pkl")

import streamlit as st
import joblib
from openai import OpenAI

# Load model
model = joblib.load("model.pkl")

# OpenAI
client = OpenAI(api_key="YOUR_API_KEY")

def get_ai_advice(premium):
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {
                "role": "user",
                "content": f"My insurance premium is {premium}. Explain why and how to reduce it."
            }
        ]
    )
    return response.choices[0].message.content

# UI
st.set_page_config(page_title="Health Insurance AI", layout="centered")

st.title("💊 Health Insurance AI Advisor")

age = st.slider("Age", 18, 60)
bmi = st.number_input("BMI", 10.0, 50.0)
children = st.number_input("Children", 0, 5)

if st.button("Predict"):
    pred = model.predict([[age, bmi, children]])[0]

    st.success(f"💰 Estimated Premium: ₹{round(pred, 2)}")

    with st.spinner("AI is thinking..."):
        advice = get_ai_advice(pred)

    st.write("🤖 AI Advice:")
    st.write(advice)